%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 810.531754685715
Camera1.fy: 809.559827734332
Camera1.cx: 777.726418434506
Camera1.cy: 604.080054449286

Camera1.k1: -0.0383901420892291
Camera1.k2: 0.0887021390002345
Camera1.k3: -0.0431436675817510
Camera1.p1: 0.00135340162767485
Camera1.p2: -3.58690648683155e-06

Camera2.fx: 806.488330523668
Camera2.fy: 805.375530652863
Camera2.cx: 777.962287246056
Camera2.cy: 606.077546343794

Camera2.k1: -0.0377823965871936
Camera2.k2: 0.0884992331449594
Camera2.k3: -0.0431433753166695
Camera2.p1: 0.00130513915916438
Camera2.p2: -0.000684485274987400

Camera.width: 1600
Camera.height: 1200

# Camera frames per second
Camera.fps: 60

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

Stereo.ThDepth: 60.0
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.999939019619655, -0.00474717319171005, 0.00997102746814517, -99.9029944294145e-3,
         0.00482285233695345, 0.999959643895389, -0.00757962241432883, 0.605905641591489e-3,
         -0.00993464329598898, 0.00762724899919773, 0.999921560891296, -0.927954250692015e-3,
          0.0, 0.0, 0.0, 1.00000000000000]
#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid   
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid  
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast     
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0